version: "3.8"

services: 
  app:
    build:
      context: .
    hostname: "dev"
    restart: always
    ports:
      - 10022:22
      - 8502:8501
      - 8888:8888
    volumes:
      - .:/opt/project
    environment:
      - PATH=/root/.local/bin/poetry:$PATH
    working_dir: /opt/project
#    command: poetry run python -m streamlit run diabetes_prediction/app.py
    command: poetry run jupyter notebook
    privileged: true
    ipc: host
    tty: true
